language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

before_script:
  - yes "" | pecl install intl
  - composer install
  - sh test/setupdb.sh
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force