app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path:     /{_locale}/
    defaults: { _controller: AppBundle:Default:index }
    requirements:
        _locale: "%app.locales%"