# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.services.getFeedPosts:
        class: AppBundle\Services\GetFeedPosts
        arguments: [@doctrine]
    app.services.fetchFeedPosts:
        class: AppBundle\Services\FetchFeedPosts
        arguments: [@doctrine]

    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
